version: '3.8'

services:
  db:
    image: 'mysql:5.7'
    container_name: dev_db
    restart: unless-stopped
    environment:
      - MYSQL_USER=dev_db
      - MYSQL_PASSWORD=dev_db
      - MYSQL_DATABASE=dev_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - '3306'